<div class="row">
    <div class="col-md-6">
        <table class="table">
            <thead>
            <tr>
                <th colspan="4">Pengajuan terlama</th>
            </tr>
            <tr>
                <th>Daerah</th>
                <th>Dokumen</th>
                <th>Tingkat</th>
                <th>Lama</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($response as $l){?>
                <tr>
                    <td><?php echo $l->namalokasi;?></td>
                    <td><?php echo $l->dok;?></td>
                    <td><?php echo $l->tingkat;?></td>
                    <td><?php echo $l->lama;?></td>
                </tr>
            <?php }?>

            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table">
            <thead>
            <tr>
                <th colspan="4">Pungutan termahal</th>
            </tr>
            <tr>
                <th>Daerah</th>
                <th>Dokumen</th>
                <th>Tingkat</th>
                <th>Lama</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($lama as $l){?>
                <tr>
                    <td><?php echo $l->namalokasi;?></td>
                    <td><?php echo $l->dok;?></td>
                    <td><?php echo $l->tingkat;?></td>
                    <td><?php echo $l->pungutan;?></td>
                </tr>
            <?php }?>

            </tbody>
        </table>
    </div>
</div>
