<?php
$kelurahan=array();
$pung=array();
foreach ($response as $u) {
        //echo $u->pungutan." <br>";
    $kelurahan[]=$u->namalokasi;
    $pungutan[]=$u->pungutan;
    }
?>
<script>
    $(function () {
        $('#chart').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Peringkat Pungutan'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: [2000,2001,2002,2003],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Nilai'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Pungutan',
                data: [12,43,34,34
                ]

            }]
        });
    });
</script>
