<?php
$kelurahan=array();
$pung=array();
$nm=1;
$p=1;
foreach ($response as $u) {
       // echo $u->namalokasi." - ".$u->num." - ".$u->tingkat." <br>";

        if($u->pungutan==''){
            $pungutan[]=0;
            $p++;
        }else{
            $pungutan[]=$u->pungutan;
            if($u->namalokasi==''){
                $kelurahan[]="dummy".$nm;
                $nm++;
            }else{
                $kelurahan[]=$u->namalokasi;
            }
        }
    }
?>
<div id="chart"></div>
<script>
    $(function () {
        $('#chart').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Peringkat Pungutan'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: [<?php
                foreach($kelurahan as $v)
                {
                    echo '"'.$v.'",';
                }
                ?>],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Nilai'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Pungutan',
                data: [<?php
                foreach($pungutan as $v)
                {
                    echo $v.',';
                }
                ?>
                ]

            }]
        });
    });
</script>

<div class="row">
    <div class="col-md-6">
        <table class="table">
            <thead>
                <tr>
                    <th colspan="4">Pengajuan terlama</th>
                </tr>
                <tr>
                    <th>Daerah</th>
                    <th>Dokumen</th>
                    <th>Tingkat</th>
                    <th>Lama</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($lama as $l){?>
                <tr>
                    <td><?php echo $l->nama_lokasi;?></td>
                    <td><?php echo $l->dok;?></td>
                    <td><?php echo $l->tingkat;?></td>
                    <td><?php echo $l->lama;?></td>
                </tr>
            <?php }?>

            </tbody>
        </table>
    </div>
</div>
